version: '3'

services:
    server:
        container_name: ${SERVER_CONTAINER_NAME}
        build:
            context: .
            dockerfile: Dockerfile
            args: 
                EXPOSE_PORT: ${SERVER_EXPOSE_PORT}
        image: node:12.19.0-alpine3.12
        ports:
            - ${SERVER_EXPOSE_PORT}:${SERVER_EXPOSE_PORT}
